# nixpacks.toml

[phases.setup]
nixPkgs = ["python39", "gcc"]

[phases.install]
cmds = ["python -m venv /opt/venv", ". /opt/venv/bin/activate", "pip install -r requirements.txt"]

[start]
cmd = "uvicorn api:app --host 0.0.0.0 --port 8000"
